# Generated by Django 5.0.1 on 2024-02-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreAccessLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeaccesslog',
            options={},
        ),
    ]
