# Generated by Django 5.0.1 on 2024-02-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='stores',
            field=models.ManyToManyField(related_name='wishlists', to='stores.store'),
        ),
    ]
