# Generated by Django 5.0.1 on 2024-02-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        ('wishlists', '0004_remove_wishlist_name_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='stores',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlists', to='stores.store'),
        ),
    ]
