# Generated by Django 5.0.1 on 2024-03-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='p_category',
            field=models.IntegerField(blank=True, default='99', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
