# Generated by Django 5.0.1 on 2024-03-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='news_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
