# Generated by Django 5.0.1 on 2024-02-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_created_at_alter_store_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='price',
        ),
        migrations.AddField(
            model_name='store',
            name='img_url',
            field=models.URLField(default=''),
        ),
    ]
