# Generated by Django 5.0.1 on 2024-03-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='frontLat',
            field=models.DecimalField(blank=True, decimal_places=8, default='37.48666000', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='frontLon',
            field=models.DecimalField(blank=True, decimal_places=8, default='127.02176200', max_digits=12, null=True),
        ),
    ]
