# Generated by Django 5.0.1 on 2024-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_store_description_store_article_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
