# Generated by Django 5.0.1 on 2024-02-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_end_date_store_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
